"""Type stubs for Rust bindings (_core module)."""

from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import numpy.typing as npt

ArrayFloat32 = npt.NDArray[np.float32]

class Microscope:
    """Rust Microscope wrapper."""

    def __init__(
        self,
        architecture: str = "llama",
        num_layers: int = 32,
        num_heads: int = 32,
        hidden_size: int = 4096,
    ) -> None: ...
    @staticmethod
    def for_llama(
        num_layers: int, num_heads: int, hidden_size: int
    ) -> Microscope: ...
    def start_trace(self, input_tokens: List[int]) -> None: ...
    def stop_trace(self) -> Optional[ActivationTrace]: ...
    def record_activation(
        self, layer: int, component: str, data: ArrayFloat32
    ) -> None: ...
    def config(self) -> Dict[str, Any]: ...

class ActivationTrace:
    """Rust ActivationTrace wrapper."""

    def get(
        self, layer: int, component: str
    ) -> Optional[ArrayFloat32]: ...
    def layers(self) -> List[int]: ...
    def components(self, layer: int) -> List[str]: ...
    def input_tokens(self) -> List[int]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> ActivationTrace: ...
    def stats(self, layer: int, component: str) -> Dict[str, Any]: ...

class AttentionPattern:
    """Rust AttentionPattern wrapper."""

    layer: int
    shape: List[int]

    def __init__(self, layer: int, data: ArrayFloat32) -> None: ...
    def as_array(self) -> ArrayFloat32: ...
    def head_pattern(self, batch: int, head: int) -> ArrayFloat32: ...
    def entropy(self) -> ArrayFloat32: ...
    def classify_head(self, head: int) -> str: ...

class Circuit:
    """Rust Circuit wrapper."""

    name: str
    description: str

    def __init__(
        self, name: str, description: str, behavior: str
    ) -> None: ...
    def add_node(
        self, layer: int, component: str, head: Optional[int] = None
    ) -> None: ...
    def add_edge(
        self,
        from_layer: int,
        from_component: str,
        from_head: Optional[int],
        to_layer: int,
        to_component: str,
        to_head: Optional[int],
        importance: float,
    ) -> None: ...
    def minimal(self, threshold: float) -> Circuit: ...
    def to_dot(self) -> str: ...
    def num_nodes(self) -> int: ...
    def num_edges(self) -> int: ...
    def total_importance(self) -> float: ...
    def edges(self) -> List[Tuple[str, str, float]]: ...

class AttentionAnalyzer:
    """Rust AttentionAnalyzer wrapper."""

    def __init__(self) -> None: ...
    def add_pattern(self, pattern: AttentionPattern) -> None: ...
    def analyze_all_heads(self) -> List[Dict[str, Any]]: ...
    def find_induction_heads(self) -> List[Tuple[int, int]]: ...
    def compute_attention_flow(self) -> ArrayFloat32: ...

class CircuitDiscoverer:
    """Rust CircuitDiscoverer wrapper."""

    def __init__(self) -> None: ...
    def add_trace(self, trace: ActivationTrace) -> None: ...
    def add_attention(self, layer: int, pattern: AttentionPattern) -> None: ...
    def discover_known_patterns(self) -> List[Circuit]: ...

class InterventionEngine:
    """Rust InterventionEngine wrapper."""

    def __init__(self) -> None: ...
    def cache_trace(self, name: str, trace: ActivationTrace) -> None: ...
    def results_summary(self) -> List[Dict[str, Any]]: ...
    def clear_results(self) -> None: ...
