"""Type stubs for architecture detection."""

from enum import Enum
from typing import Any

class Architecture(Enum):
    """Supported transformer architectures."""

    LLAMA = ...
    MISTRAL = ...
    QWEN = ...
    GEMMA = ...
    GPT2 = ...
    GPTJ = ...
    GPTNEO = ...
    FALCON = ...
    PHI = ...
    UNKNOWN = ...

def detect_architecture(model: Any) -> Architecture: ...
def architecture_to_string(arch: Architecture) -> str: ...
def string_to_architecture(name: str) -> Architecture: ...
